language: java
cache:
  directories:
   - $HOME/.m2
install: mvn package -B
matrix:
 include:
 - os: linux
   jdk: openjdk8
   script: xvfb-run mvn verify -B
 - os: osx
   osx_image: xcode8.3
   script: Xvfb :5009 & export DISPLAY=:5009 && mvn verify -B
