#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
${symbol_pound} To trigger a Travis-CI build for every GitHub push or Pull Request:
${symbol_pound} 1. Goto https://travis-ci.org/profile/${github_organization}
${symbol_pound} 2. Flip the switch for the `${github_repository}` repo
sudo: false
language: java
matrix:
 include:
 - os: linux
   jdk: oraclejdk8
   script: xvfb-run mvn verify -B
 - os: osx
   osx_image: xcode8.2
   script: Xvfb :5009 & export DISPLAY=:5009 && mvn verify -B
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
cache:
  directories:
   - $HOME/.m2
   - $HOME/.sonar/cache
install: mvn package -B
${symbol_pound}${symbol_pound} Uncomment below to perform SonarCloud (https://sonarcloud.io/) analysis,
${symbol_pound}${symbol_pound} Next steps to have automated SonarCloud analysis reports for the repository:
${symbol_pound}${symbol_pound} 1. Create organization at https://sonarcloud.io/account/organizations with '${github_organization}' as name and '${github_organization.toLowerCase()}' as key
${symbol_pound}${symbol_pound} 2. Add SONAR_TOKEN env var to Travis-CI settings, a token can be generated at https://sonarcloud.io/account/security/
${symbol_pound}${symbol_pound} 3. Push a change to GitHub to trigger a Travis-CI build and SonarCloud analysis
${symbol_pound}after_success:
${symbol_pound}- mvn sonar:sonar -Dsonar.login=${symbol_dollar}SONAR_TOKEN
