#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
${symbol_pound} To trigger a Travis-CI build for every GitHub push or Pull Request:
${symbol_pound} 1. Goto https://travis-ci.org/profile/${github_organization}
${symbol_pound} 2. Flip the switch for the `${github_repository}` repo
sudo: false
language: java
jdk: oraclejdk8
cache:
  directories:
   - $HOME/.m2
   - $HOME/jpm
install: mvn package -B
script: xvfb-run mvn verify -B
${symbol_pound} Uncomment below to upload coverage to Codacy (https://www.codacy.com),
${symbol_pound} Next steps to integrate coverage:
${symbol_pound} 1. Register repo as project on Codacy website
${symbol_pound} 2. Add CODACY_PROJECT_TOKEN env var to Travis-CI settings, token can be found in Codacy project settings
${symbol_pound} 3. Push a change to GitHub to trigger a Travis-CI build and Codacy analysis
${symbol_pound} 3. Add coverage badge to README.md, badge snippet can be found in Codacy project settings
${symbol_pound}after_success:
${symbol_pound}- curl -sL https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar > ~/.m2/jpm4j.jar
${symbol_pound}- java -jar $HOME/.m2/jpm4j.jar -u install com.codacy:codacy-coverage-reporter:assembly
${symbol_pound}- $HOME/jpm/bin/codacy-coverage-reporter -l Java -r tests/target/jacoco/report/jacoco.xml
